export const types = {
	FEES: {
		FETCH_REQUEST: 'FEES_FETCH_REQUESTED',
		FETCH_SUCCESS: 'FEES_FETCH_SUCCESS',
		FETCH_FAILURE: 'FEES_FETCH_FAILURE',
  },
  SOCIALPOSTS: {
    FETCH_REQUEST: 'FEES_FETCH_REQUESTED',
		FETCH_SUCCESS: 'FEES_FETCH_SUCCESS',
		FETCH_FAILURE: 'FEES_FETCH_FAILURE',
    
  }
};
